"""removed relationships

Revision ID: 0971d4bddeab
Revises: 78b3eef76171
Create Date: 2024-12-09 15:03:46.823227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0971d4bddeab'
down_revision = '78b3eef76171'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
