"""removed course desc

Revision ID: 3dc31298b661
Revises: ab8aa38e303a
Create Date: 2024-12-22 22:36:44.019254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dc31298b661'
down_revision = 'ab8aa38e303a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'course_desc')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('course_desc', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
