"""updated full_name and student column

Revision ID: 4789c8b59a3a
Revises: 61a29a9a966f
Create Date: 2024-12-19 17:46:18.364247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4789c8b59a3a'
down_revision = '61a29a9a966f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
