"""updated users table

Revision ID: 68102d088dd8
Revises: 8317c1a9395f
Create Date: 2024-12-19 14:53:23.760975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68102d088dd8'
down_revision = '8317c1a9395f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('is_student', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_tutor', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('student_level', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'student_level')
    op.drop_column('users', 'is_tutor')
    op.drop_column('users', 'is_student')
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###
