"""added courses

Revision ID: 7e544de39c15
Revises: 960bf4025c37
Create Date: 2024-12-22 22:20:33.958315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e544de39c15'
down_revision = '960bf4025c37'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('course_name', sa.String(), nullable=True),
    sa.Column('course_code', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['department'], ['departments.dept_code'], ),
    sa.PrimaryKeyConstraint('course_code')
    )
    op.create_index(op.f('ix_courses_id'), 'courses', ['id'], unique=False)
    op.add_column('departments', sa.Column('course_code', sa.String(), nullable=True))
    op.create_foreign_key(None, 'departments', 'courses', ['course_code'], ['course_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.drop_column('departments', 'course_code')
    op.drop_index(op.f('ix_courses_id'), table_name='courses')
    op.drop_table('courses')
    # ### end Alembic commands ###
