"""updated create_user_function

Revision ID: 83412c962531
Revises: d432a7bdba9f
Create Date: 2024-12-20 12:19:02.380985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83412c962531'
down_revision = 'd432a7bdba9f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
