"""removed model

Revision ID: 8812832bfa27
Revises: fa3ffc566f6e
Create Date: 2024-12-23 12:34:14.705903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8812832bfa27'
down_revision = 'fa3ffc566f6e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
