"""create student and course tables tables

Revision ID: 8bffa25969f6
Revises: 3a15c2cf1ad2
Create Date: 2024-12-09 13:10:09.012718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bffa25969f6'
down_revision = '3a15c2cf1ad2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
