"""updated students table

Revision ID: 91faf99265d5
Revises: c845962dc5a3
Create Date: 2024-12-23 12:11:56.404471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91faf99265d5'
down_revision = 'c845962dc5a3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
