"""removed relationship

Revision ID: ab38f9e3a2c4
Revises: 0971d4bddeab
Create Date: 2024-12-19 13:49:25.156688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab38f9e3a2c4'
down_revision = '0971d4bddeab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('course_taker_id_fkey', 'course', type_='foreignkey')
    op.drop_column('course', 'taker_id')
    op.create_index(op.f('ix_students_student_id'), 'students', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_student_id'), table_name='students')
    op.add_column('course', sa.Column('taker_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('course_taker_id_fkey', 'course', 'students', ['taker_id'], ['student_id'])
    # ### end Alembic commands ###
