"""added students table

Revision ID: c845962dc5a3
Revises: 3dc31298b661
Create Date: 2024-12-23 12:08:33.760729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c845962dc5a3'
down_revision = '3dc31298b661'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
