"""updated users table

Revision ID: d293eb525ad2
Revises: 6a13fad00e40
Create Date: 2024-12-19 14:58:40.221862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd293eb525ad2'
down_revision = '6a13fad00e40'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_student', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_tutor', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('student_level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'student_level')
    op.drop_column('users', 'is_tutor')
    op.drop_column('users', 'is_student')
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###
