"""removed student_id

Revision ID: fa3ffc566f6e
Revises: 91faf99265d5
Create Date: 2024-12-23 12:26:39.561690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa3ffc566f6e'
down_revision = '91faf99265d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
