"""added full_name and student column

Revision ID: fa494a4e7ef4
Revises: d293eb525ad2
Create Date: 2024-12-19 16:54:58.347083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa494a4e7ef4'
down_revision = 'd293eb525ad2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
